services:
  db:
    container_name: event-ticket-api
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

volumes:
  db_data: